export default {
  primary: '#007bff',
  secondary: '#6c757d',
  background: '#f8f8f8',
  text: '#333',
  headerText: '#444',
  subHeaderText: '#555',
  linkText: '#007bff',
  buttonText: '#fff',
  border: '#ccc',
  footerBackground: '#eee',
  footerText: '#999',
  cardBackground: '#fff',
  shadow: '#000',
  divider: '#ddd',
};